Linear tasks
AlexanderYarokhovich/java-fundamentals pull request #2
Opened 2020-10-22 19:36 UTC by AlexanderYarokhovich

2020-11-14 10:01 UTC, SailorBLR requested changes

2020-11-14 10:01 UTC, SailorBLR commented on src/ru/javabegin/training/fastjava2/branching/Branching.java
> +            double F;
Можно в одну строку?

2020-11-14 10:01 UTC, SailorBLR commented on src/ru/javabegin/training/fastjava2/branching/Branching.java
> +            double F;
Можно в одну строку?

2020-11-14 10:01 UTC, SailorBLR commented on src/ru/javabegin/training/fastjava2/linear/Liner.java
> +    private static int sqrt(int b) {
Что делает этот метод?

2020-11-14 10:01 UTC, SailorBLR commented on src/ru/javabegin/training/fastjava2/linear/Liner.java
> +        System.out.println("Введите каординату у");
координату

2020-11-14 10:01 UTC, SailorBLR commented on src/ru/javabegin/training/fastjava2/сycles/Cycles.java
> +        BigInteger result = new BigInteger(String.valueOf(1));
Зачем такое сложное присвоение?

2020-11-14 10:01 UTC, SailorBLR commented on src/ru/javabegin/training/fastjava2/сycles/Cycles.java
> +        System.out.println(result);// В результате вконце почемуто много нулей если выбрать 200
Надо тестить, сходу не отвечу

2020-11-14 10:01 UTC, SailorBLR commented on src/ru/javabegin/training/fastjava2/сycles/Cycles.java
> +        throw new RuntimeException("не верное число");
Это не ситуация для выбрасывания ошибки. Вполне рабочий вариант для простой проверки. Ошибка - это исключительная ситуация.

2021-03-01 10:21 UTC, AlexanderYarokhovich commented on src/ru/javabegin/training/fastjava2/сycles/Cycles.java
> +        System.out.println(result);// В результате вконце почемуто много нулей если выбрать 200
нет желания уже))

2021-03-09 20:39 UTC, closed without merging